name: Ping Supabase
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send Ping
        run: curl -s "${{ secrets.VITE_SUPABASE_URL }}" > /dev/null
